name: blur
version: 0.1.9.9.6
summary: "Blur Network: The private cryptocurrency (https://blur.cash)"
description: |
    BLUR is a privacy-focused cryptocurrency based on code from Monero. The Blur
    Network focuses on fostering an educational environment within its community,
    to lower the barriers to entry for those with an interest in cryptocurrency/mining.
    BLUR can be mined with just a CPU, and does not require specialized hardware.
    Join the Fight for Financial Freedom.
grade: stable
confinement: strict
base: core20

apps:
    blurd:
        command: bin/blurd-wrapper
        plugs:
            - network
            - network-bind
    blur-wallet-rpc:
        command: usr/local/bin/blur-wallet-rpc
        plugs:
            - home
            - network
            - network-bind
    blur-wallet-cli:
        command: usr/local/bin/blur-wallet-cli
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        cmake-parameters:
            - -DARCH="x86-64"
            - -DBUILD_TAG="linux-x64"
            - -DBUILD_64=ON
            - -DCMAKE_BUILD_TYPE="Release"
            - -DBUILD_TESTS=OFF
            - -DSTATIC=ON
        source: .
        build-packages:
            - gcc
            - g++
            - pkg-config
            - libboost-date-time1.71-dev
            - libboost-serialization1.71-dev
            - libboost-chrono1.71-dev
            - libboost-system1.71-dev
            - libboost-thread1.71-dev
            - libboost-locale1.71-dev
            - libboost-atomic1.71-dev
            - libboost-filesystem1.71-dev
            - libboost-program-options1.71-dev
            - libboost-regex1.71-dev
            - libssl-dev
            - libsodium-dev
            - git
            - build-essential
            - libreadline8
            - libtinfo-dev
        stage-packages:
            - libboost-date-time1.71.0
            - libboost-serialization1.71.0
            - libboost-chrono1.71.0
            - libboost-system1.71.0
            - libboost-thread1.71.0
            - libboost-locale1.71.0
            - libboost-atomic1.71.0
            - libboost-filesystem1.71.0
            - libboost-program-options1.71.0
            - libboost-regex1.71.0
            - libtinfo-dev
            - libssl-dev
            - libsodium23
            - libstdc++6
            - libgcc1
            - libreadline8
        prime:
            - usr/local/bin
            - etc
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/blurd.conf: etc/blurd.conf
            contrib/snap/blurd-wrapper: bin/blurd-wrapper
        prime:
            - etc
            - bin

