name: blur
version: 0.1.9.9.5
summary: "Blur Network: The private cryptocurrency (https://blur.cash)"
description: |
    BLUR is a privacy-focused cryptocurrency based on code from Monero. The Blur
    Network focuses on fostering an educational environment within its community,
    to lower the barriers to entry for those with an interest in cryptocurrency/mining.
    BLUR can be mined with just a CPU, and does not require specialized hardware.
    Join the Fight for Financial Freedom.
grade: stable
confinement: strict
base: core18

apps:
    blurd:
        command: |
          blurd-wrapper --data-dir ${HOME}/.blur-net
        plugs:
            - network
            - network-bind
    blur-wallet-rpc:
        command: |
          blur-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    blur-wallet-cli:
        command: |
          blur-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        disable-parallel: true
        configflags:
            - -DCMAKE_BUILD_TYPE=Release
            - -DBUILD_TESTS=OFF
            - -DSTATIC=ON
        source: .
        build-packages:
            - gcc
            - g++
            - pkg-config
            - libboost-all-dev
            - libssl-dev
            - libsodium-dev
            - git
            - build-essential
            - libunwind-dev
            - libreadline7
            - libtinfo5
        stage-packages:
            - libboost-date-time1.62.0
            - libboost-serialization1.62.0
            - libboost-chrono1.62.0
            - libboost-system1.62.0
            - libboost-thread1.62.0
            - libboost-locale1.62.0
            - libboost-atomic1.62.0
            - libboost-filesystem1.62.0
            - libboost-program-options1.62.0
            - libboost-regex1.62.0
            - libssl-dev
            - libsodium23
            - libstdc++6
            - libgcc1
            - libreadline7
            - libunwind-dev
            - libtinfo5
        prime:
            - bin
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/blurd.conf: etc/blurd.conf
            contrib/snap/blurd-wrapper: bin/blurd-wrapper
        prime:
            - etc
            - bin
